### ISSUE TITLE
secrets.py sample

### ISSUE THREAD

**Issue by HungoHung** [TwilioDevEd/call-forwarding-flask#2]
From README step 4, 

> 4. Update call_forward_flask/secrets.py to include your very own [Twilio credentials](https://www.twilio.com/console). We'll read from this file when setting the config for the app. Remember to keep secrets a secret and don't check in your changes to that file.

Where can I find the sample of secrets.py? It is not include in call_forward_flask folder.

Thank you.

**Comment by well1791** [comment]
Hi @HungoHung

Thanks for noticing that, actually there's no need for any credentials for the application to work.  So I've already updated the `readme` in master.

Please let us know if find more issues using the project. ^^
